services:
  - type: web
    name: robofantasma1
    env: python
    plan: starter
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
