services:
  - type: worker
    name: robofantasma1
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: starter
    envVars:
      - key: ENV
        value: production